name: Workflow executed when pushing git tag for a new version

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*

jobs:
  build-and-publish-artifact:
    uses: AngoraSix/infra/.github/workflows/action-publish-maven.yml@main
    secrets:
      maven-gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      ossrh-username: ${{ secrets. }}
      ossrh-token: ${{ secrets. }}
      maven-gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}