name: Workflow executed when pushing git tag for a new version

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*

jobs:
  build-and-publish-artifact:
    uses: AngoraSix/infra/.github/workflows/action-publish-maven.yml@main